// Code generated by "enumer -type=DomainEventType -transform=kebab"; DO NOT EDIT.

package events

import (
	"fmt"
	"strings"
)

const _DomainEventTypeName = "company-created-event-typecompany-updated-event-typecompany-deleted-event-type"

var _DomainEventTypeIndex = [...]uint8{0, 26, 52, 78}

const _DomainEventTypeLowerName = "company-created-event-typecompany-updated-event-typecompany-deleted-event-type"

func (i DomainEventType) String() string {
	if i < 0 || i >= DomainEventType(len(_DomainEventTypeIndex)-1) {
		return fmt.Sprintf("DomainEventType(%d)", i)
	}
	return _DomainEventTypeName[_DomainEventTypeIndex[i]:_DomainEventTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DomainEventTypeNoOp() {
	var x [1]struct{}
	_ = x[CompanyCreatedEventType-(0)]
	_ = x[CompanyUpdatedEventType-(1)]
	_ = x[CompanyDeletedEventType-(2)]
}

var _DomainEventTypeValues = []DomainEventType{CompanyCreatedEventType, CompanyUpdatedEventType, CompanyDeletedEventType}

var _DomainEventTypeNameToValueMap = map[string]DomainEventType{
	_DomainEventTypeName[0:26]:       CompanyCreatedEventType,
	_DomainEventTypeLowerName[0:26]:  CompanyCreatedEventType,
	_DomainEventTypeName[26:52]:      CompanyUpdatedEventType,
	_DomainEventTypeLowerName[26:52]: CompanyUpdatedEventType,
	_DomainEventTypeName[52:78]:      CompanyDeletedEventType,
	_DomainEventTypeLowerName[52:78]: CompanyDeletedEventType,
}

var _DomainEventTypeNames = []string{
	_DomainEventTypeName[0:26],
	_DomainEventTypeName[26:52],
	_DomainEventTypeName[52:78],
}

// DomainEventTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DomainEventTypeString(s string) (DomainEventType, error) {
	if val, ok := _DomainEventTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DomainEventTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DomainEventType values", s)
}

// DomainEventTypeValues returns all values of the enum
func DomainEventTypeValues() []DomainEventType {
	return _DomainEventTypeValues
}

// DomainEventTypeStrings returns a slice of all String values of the enum
func DomainEventTypeStrings() []string {
	strs := make([]string, len(_DomainEventTypeNames))
	copy(strs, _DomainEventTypeNames)
	return strs
}

// IsADomainEventType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DomainEventType) IsADomainEventType() bool {
	for _, v := range _DomainEventTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
